name: Build SageAttention

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main
      torch_minor:
        description: PyTorch minor version (e.g. '9' for 2.9.x)
        required: true
        type: string
        default: '9'
      torch_patch:
        description: PyTorch patch version (e.g. '0' for 2.9.0)
        required: true
        type: string
        default: '0'
      torch_is_nightly:
        description: Is this a nightly Torch build? (1=yes, 0=no)
        required: true
        type: string
        default: '1'
      cuda_minor:
        description: CUDA minor version (e.g. '8' for 12.8)
        required: true
        type: string
        default: '8'
      cuda_patch:
        description: CUDA patch version (e.g. '0' for 12.8.0)
        required: true
        type: string
        default: '0'

jobs:
  build-sageattn:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: Jimver/cuda-toolkit@v0.2.22
        with:
          cuda: 12.${{ inputs.cuda_minor }}.${{ inputs.cuda_patch }}
          use-github-cache: false
          use-local-cache: false

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheel
        shell: powershell
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cibuildwheel simpleindex

          git config --global core.autocrlf false
          git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/SageAttention.git
          cd SageAttention
          git rev-parse HEAD

          $Env:CUDA_MINOR_VERSION = "${{ inputs.cuda_minor }}"
          $Env:TORCH_MINOR_VERSION = "${{ inputs.torch_minor }}"
          $Env:TORCH_PATCH_VERSION = "${{ inputs.torch_patch }}"
          $Env:TORCH_IS_NIGHTLY = "${{ inputs.torch_is_nightly }}"
          python update_pyproject.py

          Start-Process -NoNewWindow simpleindex simpleindex.toml
          $Env:PIP_INDEX_URL = "http://127.0.0.1:8000"

          $Env:DISTUTILS_USE_SDK = "1"
          if ($Env:CUDA_MINOR_VERSION -gt "6")
          {
            $Env:SAGEATTENTION_CUDA_ARCH_LIST = "8.0 8.6 8.9 9.0 12.0"
          }
          else
          {
            $Env:SAGEATTENTION_CUDA_ARCH_LIST = "8.0 8.6 8.9 9.0"
          }
          $Env:SAGEATTENTION_WHEEL_VERSION_SUFFIX = "+cu12${{ inputs.cuda_minor }}torch2.${{ inputs.torch_minor }}.${{ inputs.torch_patch }}"
          if ($Env:TORCH_MINOR_VERSION -gt "5")
          {
            $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64,cp313-win_amd64}"
          }
          else
          {
            $Env:CIBW_BUILD = "{cp39-win_amd64,cp310-win_amd64,cp311-win_amd64,cp312-win_amd64}"
          }
          $Env:CIBW_BUILD_VERBOSITY = "1"
          $Env:CIBW_DEPENDENCY_VERSIONS = "latest"
          cibuildwheel .

      - uses: actions/upload-artifact@v4
        with:
          path: SageAttention/wheelhouse/*
